### ISSUE TITLE
MetadataNames.WORKSHEEET and MetadataNames.TABLE both resolve to the same value

### ISSUE THREAD

**Issue by UberDoodles** [thoughtspot/ts_rest_api_and_tml_tools#5]
I'm new to both Python and this module, but I was having an issue with a script I adapted from the tml_download.py example script. It was downloading the worksheets twice and never downloading the tables. On further investigation, MetadataNames.WORKSHEEET and MetadataNames.TABLE both resolve to "LOGICAL_TABLE".

So when I run 
```
for objectType in [MetadataNames.LIVEBOARD, MetadataNames.ANSWER, MetadataNames.WORKSHEEET, MetadataNames.TABLE]:
    print(objectType)
```
I get 
> PINBOARD_ANSWER_BOOK
> QUESTION_ANSWER_BOOK
> LOGICAL_TABLE
> LOGICAL_TABLE

I would raise a pull request to fix this, but I can't actually find where these values are defined in the repository; I can see lots of references to MetadataNames, but no definition?

**Comment by UberDoodles** [comment]
Looking at the Swagger API documentation, I think I can see why this is happening. The LOGICAL_TABLE type has sub-types :

> For LOGICAL_TABLE, valid values are ONE_TO_ONE_LOGICAL, WORKSHEET, USER_DEFINED, AGGR_WORKSHEET.

I've noticed now that when my script said it was downloading worksheets, it's actually downloaded the worksheets and tables, because they both have the same basic type. To differentiate between them, and put them into different folders, the script needs to take the subtype into account. So the example script just needs tweaking.

**Comment by bryanthowell-ts** [comment]
Yes I realized (probably not as early as your issue!) that you really need to be able to pass in the MetadataSubtypes . In the the latest versions of the thoughtspot-rest-api-v1 module, the metadata_listobjectheaders() and metadata_list() methods can take any of [MetadataSubtypes.TABLE, MetadataSubtypes.VIEW, MetadataSubtypes.WORKSHEET] in the object_type parameter, which allows you to make a single list like:

    object_types_to_download = [
        MetadataNames.LIVEBOARD,
        MetadataNames.ANSWER,
        MetadataSubtypes.TABLE,
        MetadataSubtypes.WORKSHEET
    }

for t in object_types_to_download:
    objs = ts.tsrest.metadata_listobjectheaders(object_type=t)

The examples and README will be updated sometime soon to reflect this capability.

**Comment by bryanthowell-ts** [comment]
You can now use values from MetadataSubtypes in the metadata_list and metadata_listobjectheaders calls object_type argument, which lets you do a mixed list per the above comment. Closing now as resolved.
